name: Build

on:
  pull_request:
    branches:
      - main
    paths:
      - 'powertools-cloudformation/**'
      - 'powertools-core/**'
      - 'powertools-serialization/**'
      - 'powertools-logging/**'
      - 'powertools-sqs/**'
      - 'powertools-tracing/**'
      - 'powertools-validation/**'
      - 'powertools-idempotency/**'
      - 'powertools-parameters/**'
      - 'powertools-metrics/**'
      - 'powertools-test-suite/**'
      - 'powertools-e2e-tests/**'
      - 'examples/**'
      - 'pom.xml'
      - 'examples/pom.xml'
      - '.github/workflows/**'
  push:
    branches:
      - main
    paths:
      - 'powertools-cloudformation/**'
      - 'powertools-core/**'
      - 'powertools-serialization/**'
      - 'powertools-logging/**'
      - 'powertools-sqs/**'
      - 'powertools-tracing/**'
      - 'powertools-validation/**'
      - 'powertools-idempotency/**'
      - 'powertools-parameters/**'
      - 'powertools-metrics/**'
      - 'powertools-test-suite/**'
      - 'powertools-e2e-tests/**'
      - 'examples/**'
      - 'pom.xml'
      - 'examples/pom.xml'
      - '.github/workflows/**'
jobs:
  build-corretto:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        java: [8, 11, 15, 16, 17, 18, 19, 20 ]
    name: Java ${{ matrix.java }}
    env:
      JAVA: ${{ matrix.java }}
      AWS_REGION: eu-west-1
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B install --file pom.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@d9f34f8cd5cb3b3eb79b3e4b5dae3a16df499a70 # 3.1.1
        if: ${{ matrix.java == '11' }} # publish results once
        with:
          files: ./powertools-cloudformation/target/site/jacoco/jacoco.xml,./powertools-core/target/site/jacoco/jacoco.xml,./powertools-idempotency/target/site/jacoco/jacoco.xml,./powertools-logging/target/site/jacoco/jacoco.xml,./powertools-metrics/target/site/jacoco/jacoco.xml,./powertools-parameters/target/site/jacoco/jacoco.xml,./powertools-serialization/target/site/jacoco/jacoco.xml,./powertools-sqs/target/site/jacoco/jacoco.xml,./powertools-tracing/target/site/jacoco/jacoco.xml,./powertools-validation/target/site/jacoco/jacoco.xml
      - name: Get artifacts size & build report
        id: artifacts-size-report
        if: ${{ matrix.java == '11.0.x' }} # do it once
        run: |
          report='## Artifacts Size Report\n\n'
          report+='| Module | Version | Size |\n'
          report+='| --- | --- | --- |\n'
          artifact_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          for artifact in $(cat target/powertools-parent-*.buildinfo | grep 'outputs.*.jar' | grep -v 'sources.jar'); do
            artifact_name=$(echo "$artifact" | cut -d '=' -f2)
            artifact_name=${artifact_name%-$artifact_version.jar}
            artifact_size=$(grep "${artifact%%.filename*}.length" target/powertools-parent-*.buildinfo | cut -d '=' -f2)
            echo "$artifact_name = $artifact_size"
            report+="| ${artifact_name} | ${artifact_version} | ${artifact_size} |\n"
          done
          echo "ARTIFACT_REPORT=$report" >> "$GITHUB_OUTPUT"
      - name: Comment artifacts size report
        if: ${{ matrix.java == '11.0.x' }} # do it once
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "${{ steps.artifacts-size-report.outputs.ARTIFACT_REPORT }}"
            })

  savepr:
    runs-on: ubuntu-latest
    name: Save PR number if running on PR by dependabot
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Create Directory and save issue
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }}
          echo ${{ github.event.number }} > ./pr/NR
      - uses: actions/upload-artifact@v2
        name: Upload artifact
        with:
          name: pr
          path: pr/
