name: Run end-to-end tests

on:
  workflow_dispatch:

  push:
    branches: [main]
    paths: # add other modules when there are under e2e tests
      - 'powertools-e2e-tests/**'
      - 'powertools-core/**'
      - 'powertools-serialization/**'
      - 'powertools-logging/**'
      - 'powertools-tracing/**'
      - 'powertools-idempotency/**'
      - 'powertools-parameters/**'
      - 'powertools-metrics/**'
      - 'pom.xml'
      - '.github/workflows/**'

permissions:
  contents: read

jobs:
  e2e:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        java: [ 8, 11, 17 ]
    name: End-to-end tests java${{ matrix.java }}
    env:
      JAVA_VERSION: ${{ matrix.java }}
      AWS_DEFAULT_REGION: eu-west-1
    permissions:
      id-token: write # needed to interact with GitHub's OIDC Token endpoint.
      contents: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
        with:
          egress-policy: audit

      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Setup java
        uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.11.0
        with:
          distribution: 'corretto'
          java-version: ${{ matrix.java }}
          cache: maven
      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@05b148adc31e091bafbaf404f745055d4d3bc9d2 # v1.6.1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_TO_ASSUME }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
      - name: Run e2e test with Maven
        run: mvn -DskipTests install --file pom.xml && mvn -Pe2e -B verify --file powertools-e2e-tests/pom.xml