name: SpotBugs

on:
  pull_request:
    branches:
      - main
    paths:
      - 'powertools-cloudformation/**'
      - 'powertools-core/**'
      - 'powertools-serialization/**'
      - 'powertools-logging/**'
      - 'powertools-sqs/**'
      - 'powertools-tracing/**'
      - 'powertools-validation/**'
      - 'powertools-parameters/**'
      - 'powertools-idempotency/**'
      - 'powertools-metrics/**'
      - 'powertools-test-suite/**'
      - 'pom.xml'
      - '.github/workflows/**'
permissions:
  contents: read

jobs:
  codecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
        with:
          egress-policy: audit

      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Setup java JDK 1.8
        uses: actions/setup-java@91d3aa4956ec4a53e477c4907347b5e3481be8c9 # v2.5.1
        with:
          distribution: 'zulu'
          java-version: 8
          # https://github.com/jwgmeligmeyling/spotbugs-github-action/issues/6
          # https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/
          # Avoid complexity of git action with publishing report. Just build with spotbugs profile.
#      - name: Build with Maven for spotbugs check to gather reports
#        run: mvn -Pbuild-with-spotbugs -B install --file pom.xml -DskipTests -Dmaven.javadoc.skip=true -Dspotbugs.failOnError=false
#      - uses: jwgmeligmeyling/spotbugs-github-action@master
#        with:
#          path: '**/spotbugsXml.xml'
#      # Can be simplified post this issue is fixed https://github.com/jwgmeligmeyling/spotbugs-github-action/issues/9
      - name: Build with Maven for spotbugs check to mark build as fail if voilations found
        run: mvn -Pbuild-with-spotbugs -B install --file pom.xml -DskipTests -Dmaven.javadoc.skip=true -Dspotbugs.failOnError=true